require 'zendesk_api/resources/web_portal/anonymous_request'
require 'zendesk_api/resources/web_portal/category'
require 'zendesk_api/resources/web_portal/forum'
require 'zendesk_api/resources/web_portal/topic'
require 'zendesk_api/resources/web_portal/topic_comment'
require 'zendesk_api/resources/web_portal/topic_subscription'
require 'zendesk_api/resources/web_portal/topic_vote'
