require 'zendesk_api/resources/apps'
require 'zendesk_api/resources/core'
require 'zendesk_api/resources/rules'
require 'zendesk_api/resources/oauth'
require 'zendesk_api/resources/web_portal'
require 'zendesk_api/resources/voice'
